version: "3.8"

services:
  mongo:
    build: ./mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_API_USERNAME=${MONGO_API_USERNAME}
      - MONGO_INITDB_API_PASSWORD=${MONGO_API_PASSWORD}
      - MONGO_INITDB_DB=${MONGO_DB}
    expose:
      - 27017
    ports:
      - 127.0.0.1:27017:27017

  api:
    build:
      context: ./api
    depends_on:
      - mongo
    ports:
      - 8000:8000
    environment:
      - MONGO_HOST=mongo
      - MONGO_USERNAME=${MONGO_API_USERNAME}
      - MONGO_PASSWORD=${MONGO_API_PASSWORD}
      - MONGO_DB=${MONGO_DB}
      - REDIS_HOST=redis
    expose:
      - 8000

    # DEVELOPMENT: run with reload and mount source code
    command: uvicorn --host 0.0.0.0 --reload api.main:app
    volumes:
      - ./api/api/:/home/api/api/

  redis:
    image: redis:alpine
    expose:
      - 6379
    ports:
      - 6379:6379
    command: redis-server

  diagnostics:
    build:
      context: ./diagnostics
    environment:
      - REDIS_HOST=redis
    command: celery -A diagnostics.tasks worker --loglevel=INFO
    volumes:
      - ./diagnostics/diagnostics:/home/runtime/diagnostics

  model-server:
    build:
      context: ./model-server
    ports:
      - 8501:8501
    expose:
      - 8501
