version: "3.8"

x-restart-policy: &default_restart_policy
  restart: unless-stopped

services:
  mongo:
    image: mongo:4.2.23
    <<: *default_restart_policy
    hostname: "mongo"
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    networks:
      - hubintranet 
    volumes:
      - mongo-data:/data/db
  mongo-express: #Maybe not needed in Production
    image: mongo-express:0.54
    <<: *default_restart_policy
    hostname: "mongo-express"
    container_name: mongo-express
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_BASICAUTH=true
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_ROOT_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_ROOT_PASSWORD}
    networks:
      - hubintranet
      - hubnet
  keycloak:
    #build:
    #  context: ./keycloak
    #  args:
    #    - KC_VER=20.0
    image: quay.io/keycloak/keycloak:20.0
    command: start 
    <<: *default_restart_policy
    hostname: "keycloak"
    container_name: keycloak
    depends_on:
      - keycloak-db
    ports:
      - 8080:8080
      - 8443:8443
    environment:
      - KEYCLOAK_ADMIN=${KC_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KC_ADMIN_PASSWORD}
      - KC_HTTP_ENABLED=true #Not allowed in Production
      - KC_DB=postgres
      - KC_DB_URL_HOST=keycloak-db
      - KC_DB_URL_PORT=5432
      - KC_DB_URL_DATABASE=${KEYCLOAK_DB_DATABASE_NAME}
      - KC_DB_USERNAME=${KEYCLOAK_DB_USER}
      - KC_DB_PASSWORD=${KEYCLOAK_DB_PASSWORD}
      #- KC_HOSTNAME=keycloak #Needed in Production
      - KC_HOSTNAME_STRICT=false # Not allowed in Production
      - KC_HOSTNAME_STRICT_HTTPS=false # Not Allowed in Production
    networks:
      - keycloaknet
      - hubnet
  keycloak-db:
    image: postgres:15-alpine
    <<: *default_restart_policy
    hostname: "keycloak-db"
    container_name: keycloak-db
    environment:
      - POSTGRES_PASSWORD=${KEYCLOAK_DB_PASSWORD}
      - POSTGRES_USER=${KEYCLOAK_DB_USER}
      - POSTGRES_DB=${KEYCLOAK_DB_DATABASE_NAME}
    networks:
      - keycloaknet
    volumes:
      - postgres-data:/var/lib/postgresql/data
  minio:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9090"
    <<: *default_restart_policy
    hostname: "minio"
    container_name: minio
    ports:
      - 9000:9000
      - 9090:9090
    environment:
      - MINIO_ROOT_USER=${S3_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${S3_ROOT_PASSWORD}
    networks:
      - hubnet
      - hubintranet
    volumes:
      - minio-data:/data

  api:
    build:
      context: ./api
    ports:
      - 8000:8000

    # DEVELOPMENT: run with reload and mount api package code
    command: uvicorn --host 0.0.0.0 --reload api.__init__:app
    volumes:
      - ./api/api/:/home/api/api/



networks:
  hubintranet:
    internal: true
  hubnet:
  keycloaknet:
    internal: true
volumes:
  mongo-data:
  postgres-data:
  minio-data:
