name: Test Docker Stack

on:
  push:
    branches:
    - main
    - 37-funktion-des-docker-stacks-über-github-action-prüfen
  pull_request:
    branches:
    - main

jobs:
  docker:
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install Packages
      run: apt-get update && apt-get install python3 python3-pip curl -y
      
    - name: Build containers
      run: docker-compose --env-file=dev.env build

    - name: Start containers
      run: docker-compose --env-file=dev.env up -d
    # Test MongoDB

    # Test API
    - name: Install python dependencies
      run: pip install -r requirements.txt

    - name: Run pytest
      run: pytest ./api

    - name: Run flake8
      run: flake8 ./api
    # Test Keyloak/MinIO

    - name: Stop containers
      if: always()
      run: docker-compose --env-file=dev.env down -v