name: Test Docker Stack

on:
  push:
    branches:
    - main
    - 37-funktion-des-docker-stacks-über-github-action-prüfen
  pull_request:
    branches:
    - main

jobs:
  docker:
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Expose GitHub Runtime
      uses: crazy-max/ghaction-github-runtime@v2
    
    - name: Build containers with cache
      run : |
        docker buildx bake \
        --load \
        --set=*.cache-from=type=gha \
        --set=*.cache-to=type=gha

    - name: Add tags to containers
      run: docker compose --env-file=dev.env build

    - name: Start containers
      run: docker compose --env-file=dev.env up -d

    - name: Test Keycloak
      run: curl -f http://localhost:8080/

    - name: Install python dependencies
      run: pip install -r requirements.txt

    - name: Run pytest
      run: pytest ./api

    - name: Run flake8
      run: flake8 ./api

    - name: Stop containers
      if: always()
      run: docker compose --env-file=dev.env down -v